"""Generate cmake/xflr5_sources.cmake from the vendored qmake manifests.

The XFLR5 v6.62 tag tree contains orphaned files that upstream never
compiles (qmake builds only what the .pro/.pri lists name), so the CMake
build must use the same explicit lists rather than a glob.
"""
import os
import re
import sys

ROOT = r"C:\CODE\LeParagliding"
V6 = os.path.join(ROOT, "third_party", "xflr5", "xflr5v6")
OUT = os.path.join(ROOT, "cmake", "xflr5_sources.cmake")

EXCLUDE = {
    "globals/main.cpp",
    "globals/xflr5app.cpp",
    "globals/xflr5app.h",
}

def parse_qmake_lists(path):
    """Yield (variable, entry) pairs for SOURCES/HEADERS assignments."""
    with open(path, encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    # Join continuation lines. Only the immediate newline may be consumed:
    # \s would also swallow blank lines and splice the next assignment
    # (e.g. RESOURCES +=) into the SOURCES list.
    text = re.sub(r"\\[ \t]*\r?\n", " ", text)
    for line in text.splitlines():
        m = re.match(r"\s*(SOURCES|HEADERS)\s*\+?=\s*(.*)", line)
        if not m:
            continue
        for entry in m.group(2).split():
            if entry.startswith("#"):
                break
            yield m.group(1), entry

def resolve(entry, pri_dir):
    entry = entry.replace("$$PWD", pri_dir)
    if not os.path.isabs(entry):
        candidate_pro = os.path.normpath(os.path.join(V6, entry))
        candidate_pri = os.path.normpath(os.path.join(pri_dir, entry))
        # qmake resolves plain relative paths against the .pro directory.
        if os.path.exists(candidate_pro):
            return candidate_pro
        return candidate_pri
    return os.path.normpath(entry)

def main():
    manifests = []
    for base, _dirs, files in os.walk(V6):
        for name in files:
            if name.endswith((".pri", ".pro")):
                manifests.append(os.path.join(base, name))
    manifests.sort()

    collected = []
    seen = set()
    missing = []
    for manifest in manifests:
        pri_dir = os.path.dirname(manifest)
        for _var, entry in parse_qmake_lists(manifest):
            path = resolve(entry, pri_dir)
            rel = os.path.relpath(path, V6).replace("\\", "/")
            if rel in EXCLUDE or rel in seen:
                continue
            seen.add(rel)
            # isfile, not exists: on case-insensitive filesystems a stray
            # token can resolve to a directory and poison the source list.
            if not os.path.isfile(path):
                missing.append((manifest, entry))
                continue
            collected.append(rel)

    collected.sort()
    if missing:
        print("MISSING (listed in qmake but absent on disk):")
        for manifest, entry in missing:
            print(f"  {os.path.relpath(manifest, V6)}: {entry}")

    with open(OUT, "w", newline="\n") as fh:
        fh.write(
            "# Generated by cmake/gen_xflr5_sources.py from the vendored\n"
            "# qmake manifests (third_party/xflr5/xflr5v6/*.pro, */*.pri).\n"
            "# The v6.62 source tree contains orphaned duplicate files that\n"
            "# upstream never compiles, so the build must use qmake's explicit\n"
            "# lists instead of a glob. Regenerate after changing the vendored\n"
            "# tree; globals/main.cpp and globals/xflr5app.* are excluded\n"
            "# (LEparagliding provides the QApplication).\n"
            "set(XFLR5_CORE_SOURCES\n")
        for rel in collected:
            fh.write(f"    \"${{LEP_XFLR5_V6_DIR}}/{rel}\"\n")
        fh.write(")\n")

    cpp = sum(1 for r in collected if r.endswith(".cpp"))
    h = sum(1 for r in collected if r.endswith(".h"))
    print(f"Wrote {OUT}: {cpp} cpp + {h} h = {len(collected)} entries")

if __name__ == "__main__":
    main()
