; version.iss is generated by CMake at configure time (installer/version.iss.in)
; and embeds the project version plus the HEAD commit hash.
#include "version.iss"

; Machine-specific paths. Defaults match the development machine; override
; with ISCC /D switches (e.g. /DMsvcRedist_Dir=...) if they differ.
#ifndef AppBuildDir
#define AppBuildDir SourcePath + "..\build\bin\Release"
#endif
#ifndef MsvcRedist_Dir
#define MsvcRedist_Dir "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Redist\MSVC\v143"
#endif

[Setup]
ArchitecturesInstallIn64BitMode=x64
AppId={{89CE8945-07C5-44AD-BC94-4508FEBC9441}
AppName={#TargetProduct}
AppVersion={#VersionNumber}
AppVerName={#TargetProduct} v{#VersionNumber}
AppPublisher={#TargetPublisher}
DefaultGroupName={#TargetProduct}
DefaultDirName={commonpf}\{#TargetProduct}
OutputBaseFilename={#TargetName}_v{#VersionNumber}_win{#TargetArch}_installer
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\{#TargetName}.exe
; The SafeNet sign-tool definition is passed on the ISCC command line via /S
; (ISCC does not read the Inno Setup IDE's registry configuration).
SignTool=SafeNet $f

[Icons]
Name: "{group}\{#TargetProduct}"; Filename: "{app}\{#TargetName}.exe"; WorkingDir: "{app}"
Name: "{commondesktop}\{#TargetProduct}"; Filename: "{app}\{#TargetName}.exe"; Tasks: desktopicon; WorkingDir: "{app}"

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
en.installVcRuntime = Installing redistributable Visual Studio runtime ...

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

; Clear the install folder first so upgrades never leave stale files behind.
[InstallDelete]
Type: filesandordirs; Name: "{app}\*"

[Files]
; MSVC redistributable, removed again after it has run
Source: "{#MsvcRedist_Dir}\vc_redist.{#TargetArch}.exe"; DestDir: "{app}"; Flags: deleteafterinstall;

; Sign both executables exactly once: listed explicitly with the sign flag
; and excluded from the wildcard below.
Source: "{#AppBuildDir}\{#TargetName}.exe"; DestDir: "{app}"; Flags: ignoreversion sign
Source: "{#AppBuildDir}\leparagliding-engine.exe"; DestDir: "{app}"; Flags: ignoreversion sign

; Everything else from the self-contained build directory (Qt runtime and
; plugins from windeployqt, OCCT toolkits). reference-report-compare.exe is
; a test helper and stays out of the installer.
Source: "{#AppBuildDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb,{#TargetName}.exe,leparagliding-engine.exe,reference-report-compare.exe"

[Run]
Filename: "{app}\vc_redist.{#TargetArch}.exe"; Parameters: "/q /norestart"; StatusMsg: "{cm:installVcRuntime}"
